//
// Created by angaros on 3/10/2025.
//

#ifndef CLIENT_CONSTANTS_H
#define CLIENT_CONSTANTS_H

#define DEFAULT_SERVER_PORT "21000"
#define DEFAULT_SERVER_ADDR "127.0.0.1"
#define BACKUP_SERVER_ADDR "127.0.0.1"

#endif // CLIENT_CONSTANTS_H